# Generated by Django 2.2.6 on 2019-10-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts_total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('watts_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('watts_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('watts_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('frequency', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pf_avg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pf_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pf_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pf_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('v_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('v_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('v_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('current_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('var_total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('var_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('var_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('var_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('va_total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('va_r_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('va_b_phase', models.DecimalField(decimal_places=3, max_digits=7)),
                ('va_y_phase', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
