# Generated by Django 2.2.6 on 2019-10-24 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191024_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
